### ISSUE TITLE
"Add link" does not work

### ISSUE THREAD

**Issue by cyberl33t** [benjaminprojas/wp-editor#14] opened 2016-03-12 09:39 UTC
Whenever I try to add link to text, I always get

`<a href="undefined" title="undefined"></a>`

as a result. After switching the wp-editor plugin off, the "add link"-function works again. Using wordpress 4.4.2 and wp-editor 1.2.5.3

**Comment by benjaminprojas** [comment] 2016-03-31 13:08
Thanks for reporting this issue! This is a duplicate of #1.

**Closed by benjaminprojas** 2016-03-31 13:08 UTC
Labels: duplicate
